### ISSUE TITLE
Update for latest versions (especially 4.1.1)?

### ISSUE THREAD

**Issue by Defcon0** [components/masonry#2]
Would it be possible for you guys to import the latest versions into this repo?

Also a components repo for desandro/imagesloaded would be great :-)

**Comment by desandro** [comment]
I'm curious, what features are missing from the [main repo desandro/masonry](https://github.com/desandro/masonry/), that prevent you from using it?

**Comment by Defcon0** [comment]
The following part from composer.json which is code used by robloach/component-installer that is essential for us to have an automated copying from certain js/css files to our assets folder publicly visible for the web server:

```
"extra": {
        "component": {
            "main": "masonry.pkgd.js",
            "scripts": [
                "masonry.pkgd.js"
            ],
            "files": [
                "masonry.pkgd.min.js"
            ],
            "shim": {
                "exports": "Masonry"
            }
        }
    }
```

**Comment by Defcon0** [comment]
Is there a change for a components repo for desandro/imagesloaded :-)?

**Comment by RobLoach** [comment]
Currently, no. Created a repo at https://github.com/components/imagesloaded . Feel free to submit a PR for it! :+1:
